# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://windlessStorm.github.io/
baseurl: /sustain/
title: Vikrant Biswas
author: windlessStorm
description: Personal blog and resume
avatar: profile.png
email: vikrant.biswas@gmail.com
github: windlessStorm # username
twitter: vikercfc
linkedin: vikrantb
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
